package config

import (
	"go.xbrother.com/nix-operator/pkg/utils"
)

const (
	CommentHeader = "# Generated by nix-operator. DO NOT EDIT.\n"
)

type SystemConfiguration struct {
	APIVersion string   `yaml:"apiVersion"`
	Kind       string   `yaml:"kind"`
	Metadata   Metadata `yaml:"metadata"`
	Spec       Spec     `yaml:"spec"`
}

type Metadata struct {
	Name string `yaml:"name"`
}

type Spec struct {
	Network NetworkConfig  `yaml:"network"`
	System  SystemConfig   `yaml:"system"`
	Serials []SerialConfig `yaml:"serials"`
	Udev    UdevConfig     `yaml:"udev"`
}

type NetworkConfig struct {
	Interfaces []Interface `yaml:"interfaces"`
	DNS        DNSConfig   `yaml:"dns"`
	Hosts      []HostEntry `yaml:"hosts"`
	Firewall   Firewall    `yaml:"firewall"`
}

type Interface struct {
	NodeSelector utils.NodeSelector `yaml:"nodeSelector"`
	Name         string             `yaml:"name"`
	IPAddress    string             `yaml:"ipAddress"`   // IPv4 地址
	IPv6Address  string             `yaml:"ipv6Address"` // IPv6 地址
	Gateway      string             `yaml:"gateway"`     // IPv4 网关
	IPv6Gateway  string             `yaml:"ipv6Gateway"` // IPv6 网关
	MTU          int                `yaml:"mtu"`
	MACAddress   string             `yaml:"macAddress"`
}

type SerialConfig struct {
	Device   string `yaml:"device"`
	BaudRate int    `yaml:"baudRate"`
	DataBits int    `yaml:"dataBits"`
	StopBits int    `yaml:"stopBits"`
	Parity   string `yaml:"parity"`
}

type DNSConfig struct {
	Nameservers []string `yaml:"nameservers"`
}

type HostEntry struct {
	IP        string   `yaml:"ip"`
	Hostnames []string `yaml:"hostnames"`
}

type Firewall struct {
	Rules []FirewallRule `yaml:"rules"`
}

type FirewallRule struct {
	Port     int    `yaml:"port"`
	Protocol string `yaml:"protocol"`
	Action   string `yaml:"action"`
}

type SystemConfig struct {
	Timezone string    `yaml:"timezone"`
	NTP      NTPConfig `yaml:"ntp"`
}

type NTPConfig struct {
	Enabled bool     `yaml:"enabled"`
	Servers []string `yaml:"servers"`
}

type UdevConfig struct {
	Rules []UdevRule `yaml:"rules"`
}

type UdevRule struct {
	Name      string            `yaml:"name"`
	Subsystem string            `yaml:"subsystem"`
	Attrs     map[string]string `yaml:"attrs"`
	Symlink   string            `yaml:"symlink"`
}
